main: Include/CPUFluid/CPUTriVec.h* Include/CPUFluid/CPUGrid.h* Include/CPUFluid/CPUSolver.h* Include/Vec3.h* Include/Particle.h* CuDriver.cpp Makefile
	g++ -Wall -std=c++11 -mavx2 CuDriver.cpp -o main -fopenmp -lpthread
