//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch GPUFluid.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_OP_FLIPFLUIDBASIS_CLASS     2
#define IDS_CATEGORY_FLIPFLUID          3
#define IDS_OP_FLIPFLUIDBASIS_SPGROUP   4
#define IDS_OP_FLIPFLUIDBASIS_SPGROUP_SUB 5
#define IDS_OP_FLIPFLUIDBASIS_PGROUP    6
#define IDS_OP_FLIPFLUIDBASIS_PGROUP_SUB 7
#define IDS_OP_FLIPFLUIDBASIS_TYPE      8
#define IDS_RB_MULTISUBOBJECT           9
#define IDS_CLASS_NAME                  10
#define IDS_OP_FLIPFLUIDBASIS_BOUNDARY_INODES 11
#define IDS_CATEGORY_STANDARD           20
#define IDS_OP_FLIPFLUIDBASIS_TYPE_1    88
#define IDS_OP_FLIPFLUIDBASIS_TYPE_2    89
#define IDS_OP_FLIPFLUIDBASIS_TYPE_3    90
#define IDS_OP_FLIPFLUIDBASIS_VOXEL_SIZE 91
#define IDS_OP_FLIPFLUIDBASIS_SUB_SAMPLES 92
#define IDD_OP_FLIPFLUIDBASIS_UI        1181
#define IDC_OP_FLIPFLUIDBASIS_SPGROUP_SUB 1860
#define IDC_OP_FLIPFLUIDBASIS_SPGROUP   1861
#define IDC_OP_FLIPFLUIDBASIS_PGROUP    1862
#define IDC_OP_FLIPFLUIDBASIS_PGROUP_SUB 1863
#define IDC_OP_FLIPFLUIDBASIS_TYPE      1864
#define IDC_OP_FLIPFLUIDBASIS_VOXEL_SIZE 1865
#define IDC_OP_FLIPFLUIDBASIS_VOXEL_SIZE_SPIN 1866
#define IDC_OP_FLIPFLUIDBASIS_SUB_SAMPLES 1867
#define IDC_OP_FLIPFLUIDBASIS_SUB_SAMPLES_SPIN 1868
#define IDC_OP_FLIPFLUIDBASIS_INODE_LIST 2026
#define IDC_OP_FLIPFLUIDBASIS_PICKNODE  2027
#define IDC_OP_FLOWBOUNDARY_REMOVE      2028
#define IDC_OP_FLIPFLUIDBASIS_REMOVENODE 2028

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
